### ISSUE TITLE
don't be generic until you have at least two things to be generic over.

### ISSUE THREAD

**Issue by ecuzzillo** [JulianKnodt/raytrace#2]
https://github.com/JulianKnodt/raytrace/blob/162e31b22dc911458e643ec371feec35d0cc03b1/light/light.go#L16

never be preemptively generic with a time horizon of more than an hour. i.e. if you're being generic between two things and you're ABOUT to write the second thing, fine. otherwise, be specific.

**Comment by JulianKnodt** [comment]
Fair, I wanted to define the interface in case I needed to swap it out later, but I ended up condensing it with the other material type.
This will be removed at some point
