### ISSUE TITLE
this is too abstract

### ISSUE THREAD

**Issue by ecuzzillo** [JulianKnodt/raytrace#4]
https://github.com/JulianKnodt/raytrace/blob/162e31b22dc911458e643ec371feec35d0cc03b1/mesh/lazyMesh.go#L11

a face is always actually an array of consecutive vertices, and if it's not, it's useful to be explicit about that. obfuscating the way things are laid out in memory makes everything harder to reason about.

**Comment by JulianKnodt** [comment]
ah ye, I'll remove that file ty
